# For more convenient hacking on the base image
ARG QUAY_ORG=redhat-appstudio
ARG QUAY_REPO=dance-bootstrap-app

FROM quay.io/${QUAY_ORG}/${QUAY_REPO}:rhtap-runner-base

ENV CI_TYPE=github

# Currently we're not actually running inside in the container.
# Instead we copy the scripts from this image and run them directly.
COPY copy-scripts.sh /work/copy-scripts.sh
RUN  chmod 755 /work/copy-scripts.sh
