#!/bin/bash
# verify-enterprise-contract

# Top level parameters 
export VERIFY_ENTERPRISE_CONTRACT_PARAM_IMAGES=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_POLICY_CONFIGURATION=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_PUBLIC_KEY=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_REKOR_HOST=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_IGNORE_REKOR=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_TUF_MIRROR=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_SSL_CERT_DIR=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_INFO=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_STRICT=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_HOMEDIR=
export VERIFY_ENTERPRISE_CONTRACT_PARAM_EFFECTIVE_TIME=


function version() {
	echo "Running  version"
Error parsing scriptfile.json: TypeError: Cannot read properties of undefined (reading 'split')
