#!/bin/bash
set -euo pipefail

# This works when you're testing locally with bash
if [ -f results/buildah-rhtap/IMAGE_URL ]; then
    LOCAL_IMAGE="$(cat results/buildah-rhtap/IMAGE_URL)@$(cat results/buildah-rhtap/IMAGE_DIGEST)"
    LOCAL_KEY="results/cosign-sign-attest/cosign.pub"
    LOCAL_REKOR_HOST="$(cat results/cosign-sign-attest/REKOR_URL)"
fi

# Otherwise provide the image, public key file, and the rekor host as arguments
IMAGE="${1:-$LOCAL_IMAGE}"
PUBLIC_KEY="${2:-"$LOCAL_KEY"}"
REKOR_HOST="${3:-"$LOCAL_REKOR_HOST"}"

if [ -n "$REKOR_HOST" -a "$REKOR_HOST" != "none" ]; then
    REKOR_OPT="--rekor-url=$REKOR_HOST"
else
    REKOR_OPT="--insecure-ignore-tlog"
fi

# Check the image signature
cosign verify "$REKOR_OPT" --key="$PUBLIC_KEY" "$IMAGE"

# Check the attestation signature. Also outputs the raw attestation
cosign verify-attestation "$REKOR_OPT" --key="$PUBLIC_KEY" --type https://slsa.dev/provenance/v1 "$IMAGE"

# Extract the payload from the raw attestation and display it for debugging
cosign download attestation "$IMAGE" | jq '.payload | @base64d | fromjson' | yq -P
