#!/bin/bash
set -euo pipefail

# Create a temporary dir and make sure it gets cleaned up
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" EXIT
cd $TMP_DIR

# Generate a strong random password and create the signing secret
PASSWORD=$(openssl rand -hex 64)
COSIGN_PASSWORD=$PASSWORD cosign generate-key-pair

# When hacking locally the output of this script can be placed in a
# bash file and sourced. In Jenkins each value needs to be created as
# a secret text credential. Use base64 encoding with no line breaks to
# hopefully make it easier to copy/paste the values into Jenkins.
cat << EOT
#
# Generated using $0 on $(date -u -Iseconds)
# These should be created in Jenkins as secret text credentials
#
export COSIGN_SECRET_PASSWORD="$(base64 -w0 <<< $PASSWORD)"

export COSIGN_SECRET_KEY="$(base64 -w0 < cosign.key)"

export COSIGN_PUBLIC_KEY="$(base64 -w0 < cosign.pub)"
EOT
