#!/bin/bash
set -euo pipefail

# Demonstrating how you could extract the signing secret values so they can be
# copied to Jenkins credentials. The name of the credentials should match the
# names shown here since that's how they're referenced in the relevant Jenkinsfiles
# and pipeline tasks. You could also create a fresh signing secret using
# hack/create-signing-secret.

# It's important not to expose or leak the signing secret, so be careful with this
# data.

CLUSTER_NS=${1:-"openshift-pipelines"}
SECRET_NAME=${2:-"signing-secrets"}

TEMPLATE='COSIGN_SECRET_PASSWORD={{ index .data "cosign.password" }}

COSIGN_SECRET_KEY={{ index .data "cosign.key" }}

COSIGN_PUBLIC_KEY={{ index .data "cosign.pub" }}
'

kubectl get secret -n "$CLUSTER_NS" "$SECRET_NAME" -o go-template="$TEMPLATE"
