#!/bin/bash
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"

source $SCRIPTDIR/../rhtap/verify-deps-exist "MY_JENKINS_SERVER MY_JENKINS_USER MY_JENKINS_TOKEN" "java tr grep"

bash $SCRIPTDIR/jenkins-get-credentials ROX_API_TOKEN
bash $SCRIPTDIR/jenkins-get-credentials ROX_CENTRAL_ENDPOINT
bash $SCRIPTDIR/jenkins-get-credentials GITOPS_AUTH_PASSWORD
bash $SCRIPTDIR/jenkins-get-credentials QUAY_IO_CREDS
bash $SCRIPTDIR/jenkins-get-credentials COSIGN_SECRET_PASSWORD
bash $SCRIPTDIR/jenkins-get-credentials COSIGN_SECRET_KEY
bash $SCRIPTDIR/jenkins-get-credentials COSIGN_PUBLIC_KEY
