#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SECRET_NAME=$1
CREDS=$(mktemp)
java -jar $SCRIPTDIR/jenkins-cli.jar  -http -s $MY_JENKINS_SERVER \
    -auth $MY_JENKINS_USER:$MY_JENKINS_TOKEN \
     get-credentials-as-xml system::system::jenkins _  $SECRET_NAME \
     > $CREDS

ERR=$?
if [ $ERR != 0 ]; then
	echo "No credentials named $SECRET_NAME"
	exit $ERR
fi


ID=$(cat $CREDS | sed -ne '/<id>/s#\s*<[^>]*>\s*##gp')
if [ $(grep -ic "<secret>" $CREDS ) -eq 1 ]
then
    TEMP=$(cat $CREDS | tr -d '\n' | tr -d ' '  )
    one=${TEMP#*<secret>}
    SECRET=${one%</secret>*}
    echo "$ID with secret $SECRET"
else
    TEMP=$(cat $CREDS | tr -d '\n' | tr -d ' ')
    one=${TEMP#*<username>}
    USER=${one%</username>*}
    TEMP=$(cat $CREDS | tr -d '\n' | tr -d ' ')
    one=${TEMP#*<password>}
    PW=${one%</password>*}
    echo "$ID with user <$USER> and password $PW"
fi


